from colorama import Fore,Back
from colorama.ansi import Style
print(Back.BLACK + "                                                          " + Back.RED + "  " + Back.BLACK + "                                         ")
print(Back.BLACK + "                                                        " + Back.RED + "      " + Back.BLACK + "                                         ")
print(Back.BLACK + "                                                       " + Back.RED + "        " + Back.BLACK + "                                         ")
print(Back.BLACK + "                                                     " + Back.RED + "            " + Back.BLACK + "                                         ")
print(Back.BLACK + "                                                    " + Back.RED + "              " + Back.BLACK + "                                         ")
print(Back.BLACK + "                                                  " + Back.RED + "                  " + Back.BLACK + "                                         ")
print(Back.BLACK + "                                                " + Back.RED + "                      " + Back.BLACK + "                                         ")
print(Back.BLACK + "                                              " + Back.RED + "                          " + Back.BLACK + "                                         ")
print(Back.BLACK + "                                            " + Back.RED + "                              " + Back.BLACK + "                                         ")
print(Back.BLACK + "                                          " + Back.RED + "                                  " + Back.BLACK + "                                         ")
print(Back.BLACK + "                                        " + Back.RED + "                                       " + Back.BLACK + "                                         ")
print(Back.BLACK + "                                    " + Back.RED + "                                              " + Back.BLACK + "                                        ")
print(Back.BLACK + "                                         " + Back.MAGENTA + "                                     " + Back.BLACK + "                                   ")
print(Back.BLACK + "                                         " + Back.MAGENTA + "                             "+Back.WHITE + "       "+Back.MAGENTA + " " + Back.BLACK + "                                   ")
print(Back.BLACK + "                                         " + Back.MAGENTA + "                             "+Back.WHITE + "       "+Back.MAGENTA + " " + Back.BLACK + "                                   ")
print(Back.BLACK + "                                         " + Back.MAGENTA + "                             "+Back.WHITE + "       "+Back.MAGENTA + " " + Back.BLACK + "                                   ")
print(Back.BLACK + "                                         " + Back.MAGENTA + "                                     " + Back.BLACK + "                                   ")
print(Back.BLACK + "                                         " + Back.MAGENTA + "               "+Back.YELLOW + "          "+Back.MAGENTA + "            " + Back.BLACK + "                                   ")
print(Back.BLACK + "                                         " + Back.MAGENTA + "               "+Back.YELLOW + "          "+Back.MAGENTA + "            " + Back.BLACK + "                                   ")
print(Back.BLACK + "                                         " + Back.MAGENTA + "               "+Back.YELLOW + "          "+Back.MAGENTA + "            " + Back.BLACK + "                                   ")
print(Back.BLACK + "                                         " + Back.MAGENTA + "               "+Back.YELLOW + "          "+Back.MAGENTA + "            " + Back.BLACK + "                                   ")
print(Back.BLACK + "                                         " + Back.MAGENTA + "               "+Back.YELLOW + "          "+Back.MAGENTA + "            " + Back.BLACK + "                                   ")
print(Back.BLACK + "                                         " + Back.MAGENTA + "               "+Back.YELLOW + "          "+Back.MAGENTA + "            " + Back.BLACK + "                                   ")

print(Style.RESET_ALL)